export enum PROPERTY_TYPE {
    CASA_COMPLETA = 'Casa completa',
    HABITACION_CASA_PARTICULAR = 'Habitación',
    APARTAMENTO_INDEPENDIENTE = 'Apartamento independiente',
    ESTUDIO_MINIDEPARTAMENTO = 'Estudio/Mini departamento',
    CASA_COMPARTIDA = 'Casa compartida',
    CHALET = 'Chalet',
    VILLA_QUINTA = 'Villa quinta',
    PENTHOUSE = 'Penthouse',
    CASA_PLAYA_CABANA = 'Casa en la playa / Cabaña',
    HOSTAL_POSADA = 'Hostal',
    CASA_BOUTIQUE = 'Casa boutique',
    ALOJAMIENTO_RURAL_ECOLOGICO = 'Alojamiento rural ecológico',
    CASA_FLOTANTE_EMBARCACION = 'Casa flotante / Embarcación',
    LOCAL_COMERCIAL = 'Local Comercial',
    OFICINA = 'Oficina',
    ESPACIO_COWORKING_AULA_SALA_REUNIONES = 'Espacio coworking / Aula / Sala de Reuniones',
    ALMACEN_NAVE_ESPACIO_DEPOSITO = 'Almacén / Nave / Déposito',
    TALLER_GARAJE = 'Taller garaje',
    TERRENO = 'Terreno',
    FINCA_GRANJA = 'Finca granja',
    ESPACIO_PARA_EVENTOS = 'Espacio para evento',
    PARCELA_KIOSCO_PUNTO_VENTA = 'Parcela kiosco / Punto de Venta',
}