"use client";
// import type {Metadata} from "next";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";
import { SessionProvider } from "next-auth/react";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={'antialiased'}>
            <SessionProvider>
                <QueryProvider>
                    {children}
                </QueryProvider>
            </SessionProvider>
        </body>
        </html>
    );
}
